<?php

use Illuminate\Database\Seeder;

use App\ActivoTipo;

class ActivoTiposTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Datos (carga manual)
        $data = [
			[
				// 'id' => 1,
				'nombre' => 'PC ESCRITORIO',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => true,
				'has_sistema_operativo' => true,
				'has_sistema_operativo_serie' => true,
				'has_cpu' => true,
				'has_memoria' => true,
				'has_motherboard' => true,
				'has_hd_marca' => true,
				'has_hd_capacidad' => true,
				'has_dvd_rw' => true,
				'has_dvd_rw_marca' => true,
				'has_ethernet_mac' => true,
				'has_ethernet_dinamico' => true,
				'has_ethernet_ip' => true,
				'has_ethernet_mask' => true,
				'has_ethernet_gw' => true,
				'has_ethernet_dns' => true,
				'has_wireless_mac' => true,
				'has_wireless_dinamico' => true,
				'has_wireless_ip' => true,
				'has_wireless_mask' => true,
				'has_wireless_gw' => true,
				'has_wireless_dns' => true,
				'has_fuente' => true,
				'has_observaciones' => true,
			],[
				// 'id' => 2,
				'nombre' => 'PORTÁTILES',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => true,
				'has_sistema_operativo' => true,
				'has_sistema_operativo_serie' => true,
				'has_cpu' => true,
				'has_memoria' => true,
				'has_motherboard' => true,
				'has_hd_marca' => true,
				'has_hd_capacidad' => true,
				'has_dvd_rw' => true,
				'has_dvd_rw_marca' => true,
				'has_ethernet_mac' => true,
				'has_ethernet_dinamico' => true,
				'has_ethernet_ip' => true,
				'has_ethernet_mask' => true,
				'has_ethernet_gw' => true,
				'has_ethernet_dns' => true,
				'has_wireless_mac' => true,
				'has_wireless_dinamico' => true,
				'has_wireless_ip' => true,
				'has_wireless_mask' => true,
				'has_wireless_gw' => true,
				'has_wireless_dns' => true,
				'has_fuente' => false,
				'has_observaciones' => true,
			],[
				// 'id' => 3,
				'nombre' => 'MONITOR',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			],[
				// 'id' => 4,
				'nombre' => 'IMPRESORA',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			]
		];

        foreach ($data as $v)
			ActivoTipo::create($v);

    }
}
