<?php

use Illuminate\Database\Seeder;

use App\ActivoTipo;

class ActivoTiposExtra1TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Datos (carga manual)
        $data = [
			[
				// 'id' => 5,
				'nombre' => 'CÁMARA',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			],[
				// 'id' => 6,
				'nombre' => 'CONECTIVIDAD',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			],[
				// 'id' => 7,
				'nombre' => 'UPS',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			],[
				// 'id' => 8,
				'nombre' => 'INSUMO',
				'has_nro_inventario' => true,
				'has_orden_compra' => true,
				'has_marca' => true,
				'has_modelo' => true,
				'has_nro_serie' => true,
				'has_ubicacion' => true,
				'has_fecha_alta' => true,
				'has_nombre_equipo' => false,
				'has_sistema_operativo' => false,
				'has_sistema_operativo_serie' => false,
				'has_cpu' => false,
				'has_memoria' => false,
				'has_motherboard' => false,
				'has_hd_marca' => false,
				'has_hd_capacidad' => false,
				'has_dvd_rw' => false,
				'has_dvd_rw_marca' => false,
				'has_ethernet_mac' => false,
				'has_ethernet_dinamico' => false,
				'has_ethernet_ip' => false,
				'has_ethernet_mask' => false,
				'has_ethernet_gw' => false,
				'has_ethernet_dns' => false,
				'has_wireless_mac' => false,
				'has_wireless_dinamico' => false,
				'has_wireless_ip' => false,
				'has_wireless_mask' => false,
				'has_wireless_gw' => false,
				'has_wireless_dns' => false,
				'has_fuente' => false,
				'has_observaciones' => true,
			],
		];

        foreach ($data as $v)
			ActivoTipo::create($v);

    }
}
